sonar.projectKey=Practica1_Analisis_SonarQube
sonar.projectName=Practica1_Analisis_SonarQube
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/venv/**,**/.venv/**,**/env/**,**/__pycache__/**,**/*.pyc,**/node_modules/**,**/.scannerwork/**,**/nicepage.css,**/static/assets/**
sonar.python.version=3.14.2
sonar.host.url=http://localhost:9000