sonar.projectKey=PideloYa-Analisis
sonar.projectName=PideloYa-Analisis
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=*/venv/,/.venv/,/env/,/_pycache_/,/.pyc,*/node_modules/,/.scannerwork/*
sonar.python.version=3.10
sonar.host.url=http://localhost:9000